server:
  port:8083

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://satellitedb.cfl1nlrulmmx.us-east-1.rds.amazonaws.com:3306/satellitedb
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true